# @package _global_
dataset:
  name: "reid_pairs"
  source_json_path: "~/data/reid_data/20250727/reid_pairs.json"   
  
  # Use main config values if defined, otherwise use defaults
  train_size: ${train_size}
  val_size: ${val_size}
  test_size: ${test_size}
  random_state: ${seed}
  
  image_size: [256, 128]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  
  # augmentation:
  #   train:
  #     horizontal_flip: 0.5
  #     color_jitter:
  #       brightness: 0.2
  #       contrast: 0.2
  #       saturation: 0.2
  #       hue: 0.1
  #     random_erasing:
  #       probability: 0.5
  #       scale: [0.02, 0.33]
  #       ratio: [0.3, 3.3]
  
  batch_size: 64
  num_workers: 8
  pin_memory: false
  shuffle:
    train: true
    val: false
    test: false